### ISSUE TITLE
Publish this?

### ISSUE THREAD

**Issue by Amnesthesia** [kesha-antonov/react-native-action-cable#1]
This looks really promising, but it doesn't seem to be published?

```
» yarn add react-native-action-cable                                                                                          
yarn add v1.10.1
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-action-cable: Not found".
```

**Comment by kesha-antonov** [comment]
@Amnesthesia Yeah, forgot about this. Will do.

BTW
Can you help improve Readme?

**Comment by Amnesthesia** [comment]
I don't actually know how to do any of that, I didn't end up using this library since it wasn't published

**Comment by kesha-antonov** [comment]
@Amnesthesia https://www.npmjs.com/package/@kesha-antonov/react-native-action-cable
