### ISSUE TITLE
Unable to use the package

### ISSUE THREAD

**Issue by vinay-webrmedia** [kesha-antonov/react-native-action-cable#2]
After installing i followed the instruction and ```var actionCable = ActionCable.createConsumer('ws://localhost:3000/cable');``` this line fails.

![screenshot_2019-01-29-16-32-08-061_com gopher](https://user-images.githubusercontent.com/18738048/51904597-0cc17a00-23e5-11e9-9111-dd4730688844.png)

**Comment by kesha-antonov** [comment]
@vinay-webrmedia Hey! Thanks for the reply. It's something with imports
I'll check that

**Comment by vinay-webrmedia** [comment]
Thank you

**Comment by kesha-antonov** [comment]
@vinay-webrmedia I've updated Readme - how to use import
https://github.com/kesha-antonov/react-native-action-cable/blob/master/README.md#usage
Check it please

Do you use the same?

**Comment by AhmedAliIbrahim** [comment]
Docs isn't clear enough about how we should use this package

**Comment by kesha-antonov** [comment]
@AhmedAliIbrahim Hey!
Thanks for the feedback
I'll rewrite Readme to make it clear how to use it

**Comment by AhmedAliIbrahim** [comment]
@kesha-antonov any updates about Readme ?

**Comment by kesha-antonov** [comment]
Hey guys!
Sorry for the delay
Will do on the next week

**Comment by kesha-antonov** [comment]
Hey guys!

@vinay-webrmedia @AhmedAliIbrahim 

I updated Readme and uploaded new version to npm.

Please check

**Comment by AhmedAliIbrahim** [comment]
@kesha-antonov Thanks a lot, it's now much better
