### ISSUE TITLE
Not receiving data!

### ISSUE THREAD

**Issue by dcalixto** [kesha-antonov/react-native-action-cable#3]
Hello! @kesha-antonov thank you for the package, but is not receiving or something that i did wrong?

here is the configuration:

 ```
createSocket() {
    let actionCable = ActionCable.createConsumer("ws://localhost:3000/cable");

    this.chats = actionCable.subscriptions.create(
      {
        channel: "NotificationChannel"
      },
      {
        connected: () => {},
        received: data => {
    
          this.fetchNewNotification(); 
        }
      }
    );
  }
```

**Comment by kesha-antonov** [comment]
Hey @dcalixto 

Can you post please `app/channels/notifications_channel.rb`?

**Comment by dcalixto** [comment]
Sure!

```
class NotificationChannel < ApplicationCable::Channel
  def subscribed
    stream_from "notification_channel"
  end

  def unsubscribed
    # Any cleanup needed when channel is unsubscribed
  end
end
```

**Comment by kesha-antonov** [comment]
Try this

```
createSocket() {
  const actionCable = ActionCable.createConsumer("ws://localhost:3000/cable");
  const cable = new Cable({})

  const channel = cable.setChannel(
    `notification_channel`
    actionCable.subscriptions.create({
      channel: 'NotificationChannel'
    })
  )

  channel
    .on( 'connected', () => { console.log('connected') } )
    .on( 'received', data => { 
      console.log('received', data) 
      this.fetchNewNotification()
    } )
   )
 }
```

**Comment by dcalixto** [comment]
@kesha-antonov  sorry, but still not fetching or receiving data!
Even in the logs shows nothing!

**Comment by dcalixto** [comment]
@kesha-antonov  is anything that i can help or try?

**Comment by kesha-antonov** [comment]
Try
```
ActionCable.startDebugging()
```
to see the logs

**Comment by kesha-antonov** [comment]
And any output in rails server console?

**Comment by dcalixto** [comment]
@kesha-antonov just this!
![cable](https://user-images.githubusercontent.com/1009077/61596850-116e2a80-abdf-11e9-8691-b983e88d6f43.png)

**Comment by kesha-antonov** [comment]
> @kesha-antonov just this!
> ![cable](https://user-images.githubusercontent.com/1009077/61596850-116e2a80-abdf-11e9-8691-b983e88d6f43.png)

Seems like all is ok - ws connected
`.on( 'connected', () => { console.log('connected') } )` should work

I can create example example with rails app and double check that everything is fine but only on weekend

**Comment by dcalixto** [comment]
@kesha-antonov , great! :)

**Comment by kesha-antonov** [comment]
Hey! @dcalixto 
Checkout example here https://github.com/kesha-antonov/react-native-action-cable/issues/5
Still didn't have time to implement my own

**Comment by dcalixto** [comment]
hey @kesha-antonov , my fault sorry for the delay! is working. i just forget to add the data.notifications on set state of this.fetchNewNotification() function!

thank you very much for your support and for the package :)

**Comment by AftabUfaq** [comment]
how to use this in a functional component
