### ISSUE TITLE
Crash when data in received() is null

### ISSUE THREAD

**Issue by rodolphefauquez** [kesha-antonov/react-native-action-cable#7]
Hello! First, thanks for this fork, it's nice!

My problem:
```
TypeError: null is not an object (evaluating 't.action')

e#received
    subscription.js:1:1105
received
    [native code]:0
notify
    index.ios.bundle?platform=ios&dev=true&minify=false:297021:73
notify
    [native code]:0
t.prototype.events.message
    connection.js:1:3239
message
    [native code]:0
EventTarget.prototype.dispatchEvent
    event-target-shim.js:818:39
_eventEmitter.addListener$argument_1
    WebSocket.js:232:27
emit
    EventEmitter.js:190:12
callFunctionReturnFlushedQueue
    [native code]:0
```

It happen when the data of received() is null. Is it normal? I think it shouldn't crash, we don't necessary need any data for simple features use.

Crash is located in library's `subscription.js` file, in this function:

```javascript
received (t) {
    return boundMethodCheck(this,e),t.action=null!=t.action?t.action:"received",this.emit(t.action,t)
  }};
```

**Comment by kesha-antonov** [comment]
Hi!

I haven't used Rails for a while.
You can check that method here https://github.com/kesha-antonov/react-native-action-cable/blob/master/lib/action_cable/subscription.coffee#L29
Please make a PR if you'll make a fix and why `data` could be `null`

**Comment by kesha-antonov** [comment]
@rodolphefauquez just released the fix for this issue.
